from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any

class ReviewRecord(BaseModel):
    review_id: str = Field(..., description="Stable row identifier (sheet row id or hash)")
    review: str = Field(..., description="Primary review text content")
    problem: str = Field(..., description="Stated problem category/summary")
    pain_point: Optional[str] = Field(None, description="Specific identified pain point")
    product_area: Optional[str] = Field(None, description="Product area/category of the review")
    shopping_goal: Optional[str] = Field(None, description="Stated customer shopping intent")
    user_persona: Optional[str] = Field(None, description="Identified shopper persona")
    emotion: Optional[str] = Field(None, description="Customer emotional sentiment")
    barrier_to_new_category: Optional[str] = Field(None, description="Exploration barrier preventing trial")
    frequency: Optional[str] = Field(None, description="Identified severity/frequency description")
    priority: Optional[str] = Field(None, description="Relative priority status")
    recommended_action: Optional[str] = Field(None, description="Pre-processed recommended action")
    synced_at: Optional[str] = Field(None, description="Timestamp of indexing")

class QueryFilters(BaseModel):
    user_persona: Optional[str] = None
    product_area: Optional[str] = None
    barrier_to_new_category: Optional[str] = None
    priority: Optional[str] = None
    emotion: Optional[str] = None

class QueryRequest(BaseModel):
    question: str = Field(..., description="Natural language product question")
    filters: Optional[QueryFilters] = Field(None, description="Metadata filters to apply to search results")

class Theme(BaseModel):
    name: str = Field(..., description="Name of the theme")
    support_count: int = Field(..., description="Number of supporting reviews")
    description: str = Field(..., description="Summary of this theme")
    citations: List[str] = Field(..., description="List of review_ids supporting this theme")

class BarrierInsight(BaseModel):
    barrier: str = Field(..., description="Barrier description")
    count: int = Field(..., description="Occurrences mentioned")
    citations: List[str] = Field(..., description="Supporting review_ids")

class PersonaInsight(BaseModel):
    persona: str = Field(..., description="Persona label")
    behavior_summary: str = Field(..., description="Shopping habits / category comfort level")
    citations: List[str] = Field(..., description="Supporting review_ids")

class Citation(BaseModel):
    review_id: str
    review: str
    user_persona: Optional[str] = None
    product_area: Optional[str] = None
    barrier_to_new_category: Optional[str] = None

class ValidationReport(BaseModel):
    citation_accuracy_score: float = Field(..., description="Ratio of verified citations to total citations generated by LLM")
    average_retrieval_distance: float = Field(..., description="Average similarity distance of retrieved items from vector store")
    total_citations_checked: int = Field(..., description="Total citations checked by validation system")
    total_citations_failed: int = Field(..., description="Total citations failed validation")
    warnings: List[str] = Field(default_factory=list, description="Warnings or reasons for validation adjustments")

class InsightResponse(BaseModel):
    ok: bool = True
    answer_summary: str = Field(..., description="Core grounded answer summary")
    key_themes: List[Theme] = Field(default_factory=list, description="Key recurring themes identified")
    barriers: List[BarrierInsight] = Field(default_factory=list, description="Key category barriers identified")
    persona_insights: List[PersonaInsight] = Field(default_factory=list, description="Shopper segment behavior details")
    evidence_quality: str = Field(..., description="Evidence grade: strong, moderate, weak, insufficient")
    citations: List[Citation] = Field(default_factory=list, description="Direct citations mapped back to sheet source reviews")
    validation_report: Optional[ValidationReport] = Field(None, description="Automated quality validation metrics and details")

