import os
import json
import sqlite3
from typing import List, Dict, Any, Optional
from groq import Groq
from dotenv import load_dotenv

import database
import vector_store
import indexer
import query_logger
from schemas import QueryRequest, InsightResponse, Citation, Theme, BarrierInsight, PersonaInsight, ValidationReport

# Find project root
CURRENT_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

load_dotenv(dotenv_path=os.path.join(ROOT_DIR, ".env"))
load_dotenv(dotenv_path=os.path.join(CURRENT_DIR, ".env"))

# Lazy Groq Client Initialization
_groq_client = None

def get_groq_client():
    global _groq_client
    if _groq_client is None:
        api_key = os.getenv("GROQ_API_KEY")
        if not api_key:
            raise ValueError("GROQ_API_KEY environment variable is missing or empty. Please set it in apps/api/.env.")
        _groq_client = Groq(api_key=api_key)
    return _groq_client

def normalize_citation_id(cid: Any) -> str:
    cid_str = str(cid).strip()
    cid_str_lower = cid_str.lower()
    for prefix in ["review id:", "review id", "rev-", "rev", "#"]:
        if cid_str_lower.startswith(prefix):
            cid_str = cid_str[len(prefix):].strip()
            cid_str_lower = cid_str.lower()
    return cid_str

def validate_insights_quality(res_data: dict, retrieved_reviews: list, client, model_name: str) -> tuple:
    """
    Programmatically audits the citations generated by the RAG model.
    Sends all citations and corresponding review text in a single batch to Groq
    to verify that the citation is semantically justified.
    """
    retrieved_lookup = {r["review_id"]: r["chunk"] for r in retrieved_reviews}
    
    # 1. Build checks list
    checks = []
    check_index = 1
    
    # Track citation mappings to easily filter them later
    # key: check_id, value: (claim_type, list_index, citation_value)
    check_mappings = {}
    
    # Themes
    for t_idx, theme in enumerate(res_data.get("key_themes", [])):
        theme_name = theme.get("name") or "Unnamed Theme"
        theme_desc = theme.get("description") or ""
        for c_idx, cid in enumerate(theme.get("citations", [])):
            cid_str = normalize_citation_id(cid)
            if cid_str in retrieved_lookup:
                check_id = f"chk_{check_index}"
                checks.append({
                    "check_id": check_id,
                    "review_id": cid_str,
                    "review_text": retrieved_lookup[cid_str],
                    "claim_type": "theme",
                    "claim_name": theme_name,
                    "claim_details": theme_desc
                })
                check_mappings[check_id] = ("theme", t_idx, c_idx, cid)
                check_index += 1

    # Barriers
    for b_idx, barrier in enumerate(res_data.get("barriers", [])):
        barrier_name = barrier.get("barrier") or "Unknown Barrier"
        for c_idx, cid in enumerate(barrier.get("citations", [])):
            cid_str = normalize_citation_id(cid)
            if cid_str in retrieved_lookup:
                check_id = f"chk_{check_index}"
                checks.append({
                    "check_id": check_id,
                    "review_id": cid_str,
                    "review_text": retrieved_lookup[cid_str],
                    "claim_type": "barrier",
                    "claim_name": barrier_name,
                    "claim_details": f"Category exploration barrier: {barrier_name}"
                })
                check_mappings[check_id] = ("barrier", b_idx, c_idx, cid)
                check_index += 1

    # Personas
    for p_idx, persona in enumerate(res_data.get("persona_insights", [])):
        persona_name = persona.get("persona") or "Unknown Persona"
        persona_beh = persona.get("behavior_summary") or ""
        for c_idx, cid in enumerate(persona.get("citations", [])):
            cid_str = normalize_citation_id(cid)
            if cid_str in retrieved_lookup:
                check_id = f"chk_{check_index}"
                checks.append({
                    "check_id": check_id,
                    "review_id": cid_str,
                    "review_text": retrieved_lookup[cid_str],
                    "claim_type": "persona",
                    "claim_name": persona_name,
                    "claim_details": persona_beh
                })
                check_mappings[check_id] = ("persona", p_idx, c_idx, cid)
                check_index += 1

    # Fallback/Default outputs if no checks to perform
    if not checks:
        return res_data, {
            "citation_accuracy_score": 1.0,
            "total_citations_checked": 0,
            "total_citations_failed": 0,
            "warnings": []
        }

    # 2. Call auditor model in batches to prevent timeouts/buffering
    system_prompt = (
        "You are an objective, strict quality control auditor for the Blinkit Product Research RAG engine.\n"
        "Your task is to determine whether the customer review cited for a specific theme, barrier, or persona insight actually supports that claim.\n\n"
        "EVALUATION CRITERIA:\n"
        "- `is_valid` MUST be true only if the review text directly contains evidence, details, or sentiments that align with and support the claim.\n"
        "- `is_valid` MUST be false if the review text is irrelevant, does not mention the topic of the claim, or contradicts the claim.\n"
        "- Be highly critical. Do not give the benefit of the doubt. Citations must be accurate.\n\n"
        "OUTPUT FORMAT CONSTRAINT:\n"
        "You must respond with a single JSON object. Do not include markdown code block backticks. "
        "The JSON object must match this schema exactly:\n"
        "{\n"
        "  \"results\": [\n"
        "    {\n"
        "      \"check_id\": \"string\",\n"
        "      \"is_valid\": boolean,\n"
        "      \"reason\": \"string (brief explanation for decision)\"\n"
        "    }\n"
        "  ]\n"
        "}"
    )

    invalid_checks = set()
    warnings = []
    
    BATCH_SIZE = 3
    for i in range(0, len(checks), BATCH_SIZE):
        batch = checks[i:i + BATCH_SIZE]
        
        checks_str = ""
        for c in batch:
            checks_str += (
                f"Check ID: {c['check_id']}\n"
                f"Review ID: {c['review_id']}\n"
                f"Review Text: \"{c['review_text']}\"\n"
                f"Claim Type: {c['claim_type']} ({c['claim_name']})\n"
                f"Claim Details: {c['claim_details']}\n"
                f"----------------------------------------\n"
            )

        user_prompt = (
            f"Please audit the following {len(batch)} citations (batch {i // BATCH_SIZE + 1} of {(len(checks) - 1) // BATCH_SIZE + 1}) and verify their validity:\n\n"
            f"{checks_str}"
        )

        try:
            response = client.chat.completions.create(
                model=model_name,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt}
                ],
                temperature=0.0,
                response_format={"type": "json_object"}
            )
            raw_content = response.choices[0].message.content.strip()
            if raw_content.startswith("```"):
                lines = raw_content.splitlines()
                if lines[0].startswith("```"):
                    lines = lines[1:]
                if lines and lines[-1].startswith("```"):
                    lines = lines[:-1]
                raw_content = "\n".join(lines).strip()
                
            audit_res = json.loads(raw_content)
            
            for res in audit_res.get("results", []):
                chk_id = res.get("check_id")
                is_valid = res.get("is_valid", False)
                reason = res.get("reason", "")
                
                if not is_valid:
                    invalid_checks.add(chk_id)
                    mapping = check_mappings.get(chk_id)
                    if mapping:
                        claim_type, _, _, cid = mapping
                        warnings.append(
                            f"Citation verification rejected review #{cid} for {claim_type} claim: {reason}"
                        )
        except Exception as e:
            print(f"[validator] Warning: Quality validation batch failed for indices {i} to {i+len(batch)-1}:", str(e))
            warnings.append(f"Audit verification request failed for a batch of citations: {str(e)}")

    # 3. Apply changes and filter invalid citations
    total_citations_checked = len(checks)
    total_citations_failed = len(invalid_checks)
    citation_accuracy_score = (total_citations_checked - total_citations_failed) / total_citations_checked if total_citations_checked > 0 else 1.0

    # Rebuild key_themes
    new_themes = []
    for t_idx, theme in enumerate(res_data.get("key_themes", [])):
        new_cits = []
        for c_idx, cid in enumerate(theme.get("citations", [])):
            cid_str = normalize_citation_id(cid)
            check_id = None
            for chk, map_val in check_mappings.items():
                if map_val[0] == "theme" and map_val[1] == t_idx and map_val[2] == c_idx:
                    check_id = chk
                    break
            
            if check_id and check_id not in invalid_checks:
                new_cits.append(cid_str)
                
        if new_cits:
            theme["citations"] = new_cits
            theme["support_count"] = len(new_cits)
            new_themes.append(theme)
            
    res_data["key_themes"] = new_themes

    # Rebuild barriers
    new_barriers = []
    for b_idx, barrier in enumerate(res_data.get("barriers", [])):
        new_cits = []
        for c_idx, cid in enumerate(barrier.get("citations", [])):
            cid_str = normalize_citation_id(cid)
            check_id = None
            for chk, map_val in check_mappings.items():
                if map_val[0] == "barrier" and map_val[1] == b_idx and map_val[2] == c_idx:
                    check_id = chk
                    break
            if check_id and check_id not in invalid_checks:
                new_cits.append(cid_str)
                
        if new_cits:
            barrier["citations"] = new_cits
            barrier["count"] = len(new_cits)
            new_barriers.append(barrier)
            
    res_data["barriers"] = new_barriers

    # Rebuild personas
    new_personas = []
    for p_idx, persona in enumerate(res_data.get("persona_insights", [])):
        new_cits = []
        for c_idx, cid in enumerate(persona.get("citations", [])):
            cid_str = normalize_citation_id(cid)
            check_id = None
            for chk, map_val in check_mappings.items():
                if map_val[0] == "persona" and map_val[1] == p_idx and map_val[2] == c_idx:
                    check_id = chk
                    break
            if check_id and check_id not in invalid_checks:
                new_cits.append(cid_str)
                
        if new_cits:
            persona["citations"] = new_cits
            new_personas.append(persona)
            
    res_data["persona_insights"] = new_personas

    report = {
        "citation_accuracy_score": float(round(citation_accuracy_score, 3)),
        "total_citations_checked": total_citations_checked,
        "total_citations_failed": total_citations_failed,
        "warnings": warnings
    }
    
    return res_data, report


def query_rag(request: QueryRequest) -> InsightResponse:
    """
    Executes the full RAG pipeline: retrieves relevant review context, queries the Groq model
    requesting strict JSON output, and binds SQLite details to verify cited review sources.
    """
    question = request.question
    filters = request.filters.model_dump(exclude_none=True) if request.filters else {}
    
    # 1. Retrieve Candidate Reviews from Vector Store
    try:
        # Generate query vector (using the BGE instruction prefix)
        query_vector = indexer.get_query_embedding(question)
        
        # Pull top 10 matches (tuned for Phase 6: better coverage)
        raw_results = vector_store.query_similarity(query_vector, filters=filters, limit=10)
    except Exception as e:
        print("Vector retrieval failed in RAG engine:", str(e))
        return InsightResponse(
            ok=False,
            answer_summary=f"Retrieval step failed: {str(e)}",
            evidence_quality="insufficient",
            citations=[]
        )

    # 2. Extract Document Content
    retrieved_reviews = []
    retrieved_ids = set()
    distances = []
    
    if raw_results and "ids" in raw_results and raw_results["ids"]:
        ids = raw_results["ids"][0]
        documents = raw_results["documents"][0]
        metadatas = raw_results["metadatas"][0]
        distances = raw_results.get("distances", [[]])[0] if "distances" in raw_results else []
        
        for idx in range(len(ids)):
            retrieved_reviews.append({
                "review_id": ids[idx],
                "chunk": documents[idx],
                "metadata": metadatas[idx],
                "distance": float(distances[idx]) if idx < len(distances) else 0.0
            })
            retrieved_ids.add(ids[idx])

    # Calculate average retrieval distance
    avg_distance = sum(distances) / len(distances) if distances else 0.0

    # 3. Direct Fallback if No Context Exists
    if not retrieved_reviews:
        return InsightResponse(
            ok=True,
            answer_summary="No customer reviews matched the query or filters in the database.",
            evidence_quality="insufficient",
            citations=[],
            validation_report=ValidationReport(
                citation_accuracy_score=1.0,
                average_retrieval_distance=0.0,
                total_citations_checked=0,
                total_citations_failed=0,
                warnings=["No customer reviews were retrieved for this query."]
            )
        )

    # 4. Formulate Prompt Content
    context_str = ""
    for r in retrieved_reviews:
        context_str += f"[Review ID: {r['review_id']}]\n{r['chunk']}\n-------------------\n"

    # Define strict JSON schema format instructions
    schema_instructions = {
        "answer_summary": "string (core grounded summary of what the reviews reveal regarding the question)",
        "key_themes": [
            {
                "name": "string (short theme name)",
                "support_count": "number (count of supporting reviews)",
                "description": "string (detailed description sentence)",
                "citations": ["string (list of review_ids supporting this theme)"]
            }
        ],
        "barriers": [
            {
                "barrier": "string (category exploration barrier category)",
                "count": "number (number of occurrences)",
                "citations": ["string (list of review_ids)"]
            }
        ],
        "persona_insights": [
            {
                "persona": "string (shopper persona label)",
                "behavior_summary": "string (shopping habits/comfort details)",
                "citations": ["string (list of review_ids)"]
            }
        ],
        "evidence_quality": "string (MUST be one of: 'strong', 'moderate', 'weak', 'insufficient')"
    }

    system_prompt = (
        "You are an expert product research analyst for Blinkit, a quick-commerce application.\n"
        "Your task is to answer user questions based ONLY on the provided customer review records.\n\n"
        "GROUNDING LAWS:\n"
        "1. Base your answer strictly on the reviews provided. Do not use external or general knowledge.\n"
        "2. Do not invent any customer themes, personas, barriers, or recommendations.\n"
        "3. Every claim or segment analysis must cite the specific Review ID from the context.\n"
        "4. If the retrieved reviews contain thin, conflicting, or irrelevant feedback to answer the user's question, "
        "classify the 'evidence_quality' as 'weak' or 'insufficient', and state that clearly in the summary.\n\n"
        "OUTPUT FORMAT CONSTRAINT:\n"
        "You must respond with a single JSON object. Do not include markdown code block backticks (like ```json). "
        "The JSON object must match this schema exactly:\n"
        f"{json.dumps(schema_instructions, indent=2)}"
    )

    user_prompt = (
        f"USER QUESTION: {question}\n\n"
        f"RETRIEVED REVIEWS CONTEXT:\n{context_str}\n"
    )

    # 5. Call Groq Completions API
    try:
        client = get_groq_client()
        model_name_used = os.getenv("LLM_MODEL_NAME", "llama-3.3-70b-versatile")
        
        response = client.chat.completions.create(
            model=model_name_used,
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt}
            ],
            temperature=0.0,  # Highly deterministic
            max_tokens=800,  # Strict response token limit to save daily quota
            response_format={"type": "json_object"}
        )
        
        raw_json_str = response.choices[0].message.content
        print("RAW GROQ JSON RESPONSE:\n", raw_json_str)
        res_data = json.loads(raw_json_str)
    except Exception as e:
        print("Groq completion call failed:", str(e))
        return InsightResponse(
            ok=False,
            answer_summary=f"Groq API synthesis failed: {str(e)}",
            evidence_quality="insufficient",
            citations=[],
            validation_report=ValidationReport(
                citation_accuracy_score=0.0,
                average_retrieval_distance=float(round(avg_distance, 3)),
                total_citations_checked=0,
                total_citations_failed=0,
                warnings=[f"Groq synthesis failed: {str(e)}"]
            )
        )

    # Run the real-time quality validation
    res_data, audit_report = validate_insights_quality(
        res_data=res_data,
        retrieved_reviews=retrieved_reviews,
        client=client,
        model_name=model_name_used
    )

    # 6. Validate and Map Citations to SQLite Document Store
    unique_cited_ids = set()
    
    # Collect cited IDs from the validated/filtered results
    for t in res_data.get("key_themes", []):
        for c in t.get("citations", []):
            unique_cited_ids.add(str(c).strip())
            
    for b in res_data.get("barriers", []):
        for c in b.get("citations", []):
            unique_cited_ids.add(str(c).strip())
            
    for p in res_data.get("persona_insights", []):
        for c in p.get("citations", []):
            unique_cited_ids.add(str(c).strip())

    # Prevent hallucinated citations: intersect with retrieved IDs
    valid_cited_ids = unique_cited_ids.intersection(retrieved_ids)

    # Fetch full cited review records from SQLite
    citations_list = []
    if valid_cited_ids:
        try:
            conn = database.get_connection()
            conn.row_factory = sqlite3.Row
            cursor = conn.cursor()
            
            # SQLite query
            placeholders = ",".join("?" for _ in valid_cited_ids)
            query = f"""
                SELECT review_id, review, user_persona, product_area, barrier_to_new_category
                FROM reviews
                WHERE review_id IN ({placeholders})
            """
            cursor.execute(query, list(valid_cited_ids))
            db_rows = cursor.fetchall()
            conn.close()
            
            for row in db_rows:
                citations_list.append(Citation(
                    review_id=row["review_id"],
                    review=row["review"],
                    user_persona=row["user_persona"],
                    product_area=row["product_area"],
                    barrier_to_new_category=row["barrier_to_new_category"]
                ))
        except Exception as e:
            print("SQLite fetch for citations failed in RAG engine:", str(e))

    # 7. Construct Final Verified Payload
    # Parse theme arrays
    themes = []
    for t in res_data.get("key_themes", []):
        # Only retain citations that are valid
        valid_cits = [c for c in t.get("citations", []) if str(c).strip() in valid_cited_ids]
        themes.append(Theme(
            name=t.get("name") or "Unnamed Theme",
            support_count=t.get("support_count") or len(valid_cits),
            description=t.get("description") or "",
            citations=valid_cits
        ))
        
    barriers = []
    for b in res_data.get("barriers", []):
        valid_cits = [c for c in b.get("citations", []) if str(c).strip() in valid_cited_ids]
        barriers.append(BarrierInsight(
            barrier=b.get("barrier") or "Unknown Barrier",
            count=b.get("count") or len(valid_cits),
            citations=valid_cits
        ))
        
    personas = []
    for p in res_data.get("persona_insights", []):
        valid_cits = [c for c in p.get("citations", []) if str(c).strip() in valid_cited_ids]
        personas.append(PersonaInsight(
            persona=p.get("persona") or "Unknown Persona",
            behavior_summary=p.get("behavior_summary") or "",
            citations=valid_cits
        ))

    evidence_quality = res_data.get("evidence_quality") or "weak"
    if evidence_quality not in ["strong", "moderate", "weak", "insufficient"]:
        evidence_quality = "weak"

    # Direct override: thin evidence programmatic gate (tuned Phase 6: < 4 reviews)
    if len(retrieved_reviews) < 4:
        evidence_quality = "insufficient"
    elif len(retrieved_reviews) < 6 and evidence_quality == "strong":
        # Downgrade overconfident strong when we have few retrieved reviews
        evidence_quality = "moderate"

    # Build warning reports
    warnings_list = list(audit_report["warnings"])
    if avg_distance > 1.35:
        warnings_list.append(
            f"Retrieval relevance is low (average distance: {avg_distance:.3f}). "
            f"The retrieved customer reviews may not be highly relevant to your question."
        )

    # Downgrade based on validation results
    if audit_report["citation_accuracy_score"] < 0.6 and evidence_quality in ["strong", "moderate"]:
        evidence_quality = "weak"
        warnings_list.append("Evidence quality downgraded to 'weak' due to low citation accuracy.")
    if avg_distance > 1.45 and evidence_quality in ["strong", "moderate"]:
        evidence_quality = "weak"
        warnings_list.append("Evidence quality downgraded to 'weak' due to low retrieval relevance (high average distance).")

    validation_report = ValidationReport(
        citation_accuracy_score=audit_report["citation_accuracy_score"],
        average_retrieval_distance=float(round(avg_distance, 3)),
        total_citations_checked=audit_report["total_citations_checked"],
        total_citations_failed=audit_report["total_citations_failed"],
        warnings=warnings_list
    )

    # Get current sync version for log
    sync_version = "unknown"
    try:
        conn_log = database.get_connection()
        cur_log = conn_log.cursor()
        cur_log.execute("SELECT val FROM sync_meta WHERE key = 'last_sync_at'")
        row_sv = cur_log.fetchone()
        if row_sv:
            sync_version = row_sv[0]
        conn_log.close()
    except Exception:
        pass

    # Phase 6: Emit audit log entry (never crashes main path)
    query_logger.log_query(
        question=question,
        retrieved_ids=list(retrieved_ids),
        model_name=model_name_used,
        evidence_quality=evidence_quality,
        sync_version=sync_version,
        citation_accuracy=audit_report["citation_accuracy_score"],
        avg_distance=avg_distance,
    )

    return InsightResponse(
        ok=True,
        answer_summary=res_data.get("answer_summary") or "Grounded generation completed with missing summary.",
        key_themes=themes,
        barriers=barriers,
        persona_insights=personas,
        evidence_quality=evidence_quality,
        citations=citations_list,
        validation_report=validation_report
    )
